version: 1.0

model:                                               # mandatory. used to specify model specific information.
  name: bert
  framework: pytorch                                 # mandatory. possible values are tensorflow, mxnet, pytorch, pytorch_ipex, onnxrt_integerops and onnxrt_qlinearops.
quantization:                                        # optional. tuning constraints on model-wise for advance user to reduce tuning space.
  approach: post_training_dynamic_quant



tuning:
  accuracy_criterion:
    relative:  0.01                                  # optional. default value is relative, other value is absolute. this example allows relative accuracy loss: 1%.
  exit_policy:
    timeout: 0                                       # optional. tuning timeout (seconds). default value is 0 which means early stop. combine with max_trials field to decide when to exit.
    max_trials: 600
  random_seed: 9527                                  # optional. random seed for deterministic tuning.
