name: venv_ort_train
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - argon2-cffi=20.1.0=py38h27cfd23_1
  - async_generator=1.10=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - bleach=4.1.0=pyhd3eb1b0_0
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py38h06a4308_2
  - cffi=1.14.6=py38h400218f_0
  - dbus=1.13.18=hb2f20db_0
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.0=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - entrypoints=0.3=py38_0
  - expat=2.4.1=h2531618_2
  - fontconfig=2.13.1=h6c09931_0
  - freetype=2.11.0=h70c0345_0
  - glib=2.69.1=h5202010_0
  - gst-plugins-base=1.14.0=h8213a91_2
  - gstreamer=1.14.0=h28cd5cc_2
  - icu=58.2=he6710b0_3
  - importlib-metadata=4.8.2=py38h06a4308_0
  - importlib_metadata=4.8.2=hd3eb1b0_0
  - ipykernel=6.4.1=py38h06a4308_1
  - ipython=7.29.0=py38hb070fc8_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.5=pyhd3eb1b0_1
  - jedi=0.18.0=py38h06a4308_1
  - jinja2=3.0.2=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - jsonschema=3.2.0=pyhd3eb1b0_2
  - jupyter=1.0.0=py38_7
  - jupyter_client=7.1.0=pyhd3eb1b0_0
  - jupyter_console=6.4.0=pyhd3eb1b0_0
  - jupyter_core=4.9.1=py38h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libuuid=1.0.3=h7f8727e_2
  - libxcb=1.14=h7b6447c_0
  - libxml2=2.9.12=h03d6c58_0
  - markupsafe=2.0.1=py38h27cfd23_0
  - matplotlib-inline=0.1.2=pyhd3eb1b0_2
  - mistune=0.8.4=py38h7b6447c_1000
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.3.0=py38h06a4308_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.6=py38h06a4308_0
  - openssl=1.1.1m=h7f8727e_0
  - packaging=21.3=pyhd3eb1b0_0
  - pandocfilters=1.4.3=py38h06a4308_1
  - parso=0.8.3=pyhd3eb1b0_0
  - pcre=8.45=h295c915_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - prometheus_client=0.12.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.20=pyhd3eb1b0_0
  - prompt_toolkit=3.0.20=hd3eb1b0_0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.21=pyhd3eb1b0_0
  - pygments=2.10.0=pyhd3eb1b0_0
  - pyqt=5.9.2=py38h05f1152_4
  - pyrsistent=0.18.0=py38heee7806_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - pyzmq=22.3.0=py38h295c915_2
  - qt=5.9.7=h5867ecd_1
  - qtconsole=5.1.1=pyhd3eb1b0_0
  - qtpy=1.10.0=pyhd3eb1b0_0
  - readline=8.1.2=h7f8727e_1
  - send2trash=1.8.0=pyhd3eb1b0_1
  - setuptools=58.0.4=py38h06a4308_0
  - sip=4.19.13=py38he6710b0_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.37.0=hc218d9a_0
  - terminado=0.9.4=py38h06a4308_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.11=h1ccaba5_0
  - tornado=6.1=py38h27cfd23_0
  - traitlets=5.1.1=pyhd3eb1b0_0
  - wcwidth=0.2.5=pyhd3eb1b0_0
  - webencodings=0.5.1=py38_1
  - wheel=0.37.1=pyhd3eb1b0_0
  - widgetsnbextension=3.5.1=py38_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h2531618_0
  - zipp=3.7.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7f8727e_4
  - pip:
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - anyio==3.5.0
    - async-timeout==4.0.2
    - attrs==21.4.0
    - babel==2.9.1
    - cerberus==1.3.4
    - charset-normalizer==2.0.10
    - click==8.0.3
    - coloredlogs==15.0.1
    - datasets==1.17.0
    - deepspeed==0.5.9
    - dill==0.3.4
    - filelock==3.4.2
    - flatbuffers==2.0
    - frozenlist==1.2.0
    - fsspec==2022.1.0
    - h5py==3.6.0
    - hjson==3.0.2
    - huggingface-hub==0.4.0
    - humanfriendly==10.0
    - idna==3.3
    - install==1.3.5
    - joblib==1.1.0
    - json5==0.9.6
    - jupyter-server==1.13.2
    - jupyterlab==3.2.8
    - jupyterlab-server==2.10.3
      # - mpi4py==3.1.3
    - mpmath==1.2.1
    - multidict==5.2.0
    - multiprocess==0.70.12.2
    - nbclassic==0.3.5
    - ninja==1.10.2.3
    - numpy==1.22.0
    - onnx==1.10.2
      #- onnxruntime-training==1.11.0.dev20220113001+cu102
    - pandas==1.3.5
    - pillow==9.0.0
    - pip==21.3.1
    - protobuf==3.19.3
    - psutil==5.9.0
    - py-cpuinfo==8.0.0
    - pyarrow==6.0.1
    - pyparsing==3.0.6
    - pytz==2021.3
    - pyyaml==6.0
    - regex==2021.11.10
    - requests==2.27.1
    - sacremoses==0.0.47
    - scikit-learn==1.0.2
    - scipy==1.7.3
    - sniffio==1.2.0
    - sympy==1.9
    - threadpoolctl==3.0.0
    - tokenizers==0.10.3
    - torch==1.8.1
      #- torch-ort==1.9.0
    - torchvision==0.9.1
    - tqdm==4.62.3
    - transformers==4.15.0
    - triton==1.0.0
    - typing-extensions==4.0.1
    - urllib3==1.26.8
    - websocket-client==1.2.3
    - wget==3.2
    - xxhash==2.0.2
    - yarl==1.7.2
prefix: /home/ubuntu/anaconda3/envs/venv_ort_train
